sudo: require
services:
    - docker
env:
    global:
        # set environment variable to the current git repository version number so it can be appended to the docker hub images
        - SHA=$(git rev-parse HEAD)
        # google cloud CLI does not show any prompts since it will be running in Travis
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
    # unencrypts the service account file for Google cloud
    - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl
    # uses unencrypted file to activate service account
    - gcloud auth activate-service-account --key-file service-account.json
    # what project and zone should google cloud use? Lookup project in Google cloud and get the project id
    - gcloud config set project perfect-stock-275513
    # what is default data zone (location within Kubernetes cluster)
    - gcloud config set compute/zone europe-north1-a
    #  what is the name of your cluster within the zone
    - gcloud container clusters get-credentials multi-cluster
    # login to docker CLI (these need setting up as environment variables within Travis)
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    #  load up tests
    - docker build -t benauld/react-test -f ./client/Dockerfile.dev ./client

script:
    # now run the tests
    - docker run -e CI=true benauld/react-test npm run test

deploy:
    provider: script
    # run this file for the deploymeny
    script: bash ./deploy.sh
    on:
        branch: master
